# spring cloud will run the app on the port 8888 with the configuration that it will download from that is in the uri property in the bootstrap.yml
server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
